import struct

from Crypto.Cipher import AES
from Crypto.Random.Fortuna import FortunaGenerator
from Crypto.Hash import HMAC
from Crypto.Hash import SHA256
from dh import create_dh_key, calculate_dh_secret

class StealthConn(object):
    def __init__(self, conn, client=False, server=False, verbose=False):
        self.conn = conn
        self.key = None
        self.csprng = FortunaGenerator.AESGenerator()
        self.ivs = set()
        self.hmac = None
        self.client = client
        self.server = server
        self.verbose = verbose
        self.initiate_session()

    def initiate_session(self):
        # Perform the initial connection handshake for agreeing on a shared secret
        if self.server or self.client:
            my_public_key, my_private_key = create_dh_key()
            # Send them our public key
            self.send(bytes(str(my_public_key), "ascii"))
            # Receive their public key
            their_public_key = int(self.recv())
            # Obtain our shared secret
            shared_hash = calculate_dh_secret(their_public_key, my_private_key)
            print("Shared hash: {}".format(shared_hash))
            # Seed the CSPRNG with our shared secret
            self.csprng.reseed(shared_hash.encode())
            # Generate a 256-bit AES key
            self.key = self.csprng.pseudo_random_data(SHA256.digest_size)
            # Set up a SHA256 HMAC with a 256-bit key generated by the CSPRNG
            self.hmac = HMAC.new(self.csprng.pseudo_random_data(32), None, SHA256.new())

    def send(self, data):
        if self.key:
            # Generate an IV via CSPRNG that has not already used in this peer-to-peer connection
            iv = self.csprng.pseudo_random_data(AES.block_size);
            while iv in self.ivs:
                iv = self.csprng.pseudo_random_data(AES.block_size);
            # Add the IV to the set of used IVs so that IVs are not re-used and to protect against replay attacks
            self.ivs.add(iv)
            # Encrypt the data using AES-256 with the IV
            cipher = AES.new(self.key, AES.MODE_CFB, iv)
            encrypted_data = cipher.encrypt(data)
            # Calculate a HMAC for the encrypted data
            self.hmac.update(encrypted_data)
            message_hmac = self.hmac.hexdigest().encode()
            # Append the HMAC to the encrypted data, prepend the IV to the message
            encrypted_data = iv + encrypted_data + message_hmac
            if self.verbose:
                print("Original data: {}".format(data))
                print("Encrypted data: {}".format(repr(encrypted_data)))
                print("Sending packet of length {}".format(len(encrypted_data)))
        else:
            encrypted_data = data

        # Encode the data's length into an unsigned two byte int ('H')
        pkt_len = struct.pack('H', len(encrypted_data))
        self.conn.sendall(pkt_len)
        self.conn.sendall(encrypted_data)

    def recv(self):
        # Decode the data's length from an unsigned two byte int ('H')
        pkt_len_packed = self.conn.recv(struct.calcsize('H'))
        unpacked_contents = struct.unpack('H', pkt_len_packed)
        pkt_len = unpacked_contents[0]

        encrypted_data = self.conn.recv(pkt_len)
        if self.key:
            iv = encrypted_data[:AES.block_size]
            # Verify the IV has not been used to protect against replay
            if iv in self.ivs:
                return b''
            self.ivs.add(iv)
            cipher = AES.new(self.key, AES.MODE_CFB, iv)
            given_hmac = encrypted_data[-64:]
            # Calculate the HMAC of the encrypted data
            self.hmac.update(encrypted_data[AES.block_size:-64])
            message_hmac = self.hmac.hexdigest().encode()
            # Verify that the given and calculated HMACs actually agree
            if given_hmac != message_hmac:
                print("Tampering detected, closing connection.")
                self.conn.close()
            data = cipher.decrypt(encrypted_data[AES.block_size:-64])
            if self.verbose:
                print("Receiving packet of length {}".format(pkt_len))
                print("Encrypted data: {}".format(repr(encrypted_data)))
                print("Original data: {}".format(data))
        else:
            data = encrypted_data

        return data

    def close(self):
        self.conn.close()
